spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 9090
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka
zuul:
  # 禁止服务自动添加
  ignored-services: '*'
  routes:
    api-a:
      path: /customer/**
      service-id: service-customer
    api-b:
      path: /order/**
      service-id: service-order
    api-c:
      path: /test/**
      service-id: testserver
  # 开启重试功能
  retryable: true
#    # 在zuul和服务间增加feign只会增加通讯消耗，并不推荐
#    api-c:
#      path: /feign/**
#      # 由网关分发到feign，再经feign负载均衡
#      service-id: feign-server